### ISSUE TITLE
Local backup

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [LNReader/remote-service#5]
Is there any way to implement this backup that backs up everything as a local backup as well in lnreader? I mean as in revamp the current local backup that is deprecated and implement the version that backs up everything same as in the remote version.

**Comment by nyagami** [comment]
Have you tried to setup by follwing the instruction in README.md?

**Comment by 1-minute-to-midnight** [comment]
That is still remote backup, not a local backup.

**Comment by 1-minute-to-midnight** [comment]
I'm assuming if the backup can be uploaded to a server, it shouldn't be too difficult to implement it to download directly to the device.

**Comment by nyagami** [comment]
I dont think it is necessary. Is there any situation for that usage

**Comment by 1-minute-to-midnight** [comment]
1. As I use a de-googled android ROM (such as Calyx OS or Lineage OS), there is no Google Drive Integration.
2. As I am on university wifi and how it is configured, I can't self-host my own server in my local network to make the backup.

**Comment by nyagami** [comment]
1. Sadly, I have no knowledge about that
2. You can check the video in README.md, just connect your both devices to same wifi

**Comment by 1-minute-to-midnight** [comment]
I am getting this particular error in linux when trying to upload:
FileNotFoundError: [Errno 2] No such file or directory: '$HOME/.LNReader/config.json'

**Comment by 1-minute-to-midnight** [comment]
Alright to fix this error, make a file config.json in $HOME/.LNReader, then input the following:

```json
{
  "workspace": "/desired/path"
}
```

a backup folder will be saved to this desired path. When restoring, all the backups saved in this path will be shown in the app interface.

**Comment by nyagami** [comment]
Btw, you can use your phone hotspot (no need internet access).
I think local backup is not necessary nor safety.

**Comment by 1-minute-to-midnight** [comment]
Ok gotcha, I figured that'd be an option. Thanks for the help.

**Comment by 1-minute-to-midnight** [comment]
I would recommend adding that part about config.json in the README

**Comment by nyagami** [comment]
I forgot command line case. If you used GUI (.exe file), it would be added automatically
